[gorm]
dsn = "root:123456@tcp(mysql:3306)/nodnotes?charset=utf8mb4&parseTime=True"
auto_migrate = true

[jwt]
signature = "sercrethatmaycontainch@r32length"
max_age_day = 30

[hashids]
salt = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
alphabet = "abcdefghijklmnopqrstuvwxyz"
min_length = 5

[http]
port = 8080

[swagger]